import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";

type Phase = "street" | "dance" | "faceoff" | "fight" | "chase" | "jungle" | "title";
const DURATION = 60;
const phaseAt = (t:number):Phase => t < 9 ? "street" : t < 17 ? "dance" : t < 22 ? "faceoff" : t < 39 ? "fight" : t < 49 ? "chase" : t < 56 ? "jungle" : "title";
const captions:Record<Phase,string> = {street:"FOLLOW THE BASS",dance:"WORD SPREADS",faceoff:"BADMAN REACH.",fight:"EVERY HIT REMIXES THE DUB",chase:"GET OUT OF THERE",jungle:"KINGSTON IS ONLY THE BEGINNING",title:"WORD. SOUND. POWER."};

function material(color:number, emissive=0){return new THREE.MeshStandardMaterial({color,roughness:.68,metalness:.04,emissive,emissiveIntensity:emissive?1.2:0});}
function person(color:number){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.85,6,12),material(color));body.position.y=1.35;const head=new THREE.Mesh(new THREE.SphereGeometry(.27,14,10),material(0x4b281b));head.position.y=2.35;g.add(body,head);return g;}

export default function BMKGameplayClip(){
 const mount=useRef<HTMLDivElement|null>(null); const [time,setTime]=useState(0); const [playing,setPlaying]=useState(true); const phase=useMemo(()=>phaseAt(time),[time]);
 useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setTime(v=>v>=DURATION?0:v+.1),100);return()=>clearInterval(id)},[playing]);
 useEffect(()=>{const host=mount.current;if(!host)return;let dead=false,raf=0;const scene=new THREE.Scene();scene.background=new THREE.Color(0x030609);scene.fog=new THREE.FogExp2(0x081018,.027);const cam=new THREE.PerspectiveCamera(48,host.clientWidth/host.clientHeight,.1,180);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.appendChild(renderer.domElement);
 scene.add(new THREE.HemisphereLight(0x60788a,0x1a0c06,1.2));const amber=new THREE.PointLight(0xff8a32,90,30);amber.position.set(-4,6,-4);scene.add(amber);const blue=new THREE.PointLight(0x348cff,60,35);blue.position.set(7,5,-14);scene.add(blue);
 const road=new THREE.Mesh(new THREE.PlaneGeometry(22,120),new THREE.MeshPhysicalMaterial({color:0x101419,roughness:.24,metalness:.05,clearcoat:.7}));road.rotation.x=-Math.PI/2;road.position.z=-30;scene.add(road);
 for(let z=-75;z<18;z+=9){[-9,9].forEach((x,i)=>{const b=new THREE.Mesh(new THREE.BoxGeometry(6,4+(Math.abs(z)%4),7),material(i?0x24130f:0x15171b));b.position.set(x,2,z);scene.add(b);const lamp=new THREE.PointLight(0xffa348,10,9);lamp.position.set(x>0?5.8:-5.8,3.2,z+2);scene.add(lamp);});}
 const speakers=new THREE.Group();for(let x=-2;x<=2;x++)for(let y=0;y<3;y++){const box=new THREE.Mesh(new THREE.BoxGeometry(1.8,1.8,.8),material(0x090909));box.position.set(x*1.82,y*1.82+1,-22);speakers.add(box);const cone=new THREE.Mesh(new THREE.CircleGeometry(.58,20),material(0x151515));cone.position.set(x*1.82,y*1.82+1,-21.58);speakers.add(cone)}scene.add(speakers);
 const crowd=new THREE.Group();for(let i=0;i<72;i++){const p=person(i%4===0?0x5b3829:0x18191b);const side=i%2?1:-1;p.position.set(side*(3.5+(i%8)*.55),0,-12-(i%16)*1.3);p.scale.setScalar(.82+(i%5)*.035);crowd.add(p)}scene.add(crowd);
 const leroy=person(0xeee7d6);leroy.position.set(0,0,8);leroy.scale.setScalar(1.12);scene.add(leroy);const enemy=person(0x8d271d);enemy.position.set(.7,0,-7);enemy.scale.setScalar(1.08);scene.add(enemy);
 const rainGeo=new THREE.BufferGeometry();const rainCount=850;const pos=new Float32Array(rainCount*3);for(let i=0;i<rainCount;i++){pos[i*3]=(Math.random()-.5)*28;pos[i*3+1]=Math.random()*14;pos[i*3+2]=-80+Math.random()*105}rainGeo.setAttribute("position",new THREE.BufferAttribute(pos,3));const rain=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:0xb9d7ef,size:.035,transparent:true,opacity:.7}));scene.add(rain);
 const clock=new THREE.Clock();let impact=0;const animate=()=>{if(dead)return;raf=requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.033);const t=time;const p=phaseAt(t);const rp=rain.geometry.attributes.position as THREE.BufferAttribute;for(let i=0;i<rainCount;i++){let y=rp.getY(i)-dt*12;if(y<0)y=14;rp.setY(i,y)}rp.needsUpdate=true;
 crowd.children.forEach((c,i)=>{c.position.y=Math.sin(clock.elapsedTime*3+i)*((p==="dance"||p==="fight")?.06:.015)});speakers.scale.setScalar(1+Math.max(0,Math.sin(clock.elapsedTime*6))*.018);
 if(p==="street"){leroy.position.z=THREE.MathUtils.lerp(8,-10,Math.min(1,t/9));cam.position.lerp(new THREE.Vector3(0,3.3,leroy.position.z+7),.06);cam.lookAt(leroy.position.x,1.6,leroy.position.z-4)}
 else if(p==="dance"){leroy.position.z=-11;cam.position.lerp(new THREE.Vector3(-4.8,3.6,-4.5),.045);cam.lookAt(0,2,-18)}
 else if(p==="faceoff"){leroy.position.set(-.7,0,-8);enemy.position.set(.7,0,-10.3);cam.position.lerp(new THREE.Vector3(4.2,2.6,-5.4),.08);cam.lookAt(0,1.7,-9.2)}
 else if(p==="fight"){const f=t-22;const cycle=f%3.2;leroy.position.set(-.7+Math.sin(f*.8)*.35,0,-8.4);enemy.position.set(.75,0,-10.1);if(cycle<.28){leroy.rotation.z=-.12;enemy.position.z=-10.1-cycle*1.2;impact=.18}else if(cycle>1.45&&cycle<1.72){enemy.rotation.z=.15;leroy.position.z=-8.4+((cycle-1.45)*.7);impact=.12}else{leroy.rotation.z=0;enemy.rotation.z=0}cam.position.lerp(new THREE.Vector3(Math.sin(f*.34)*2.4,2.75,-3.1),.07);cam.lookAt(0,1.65,-9.2);if(impact>0){cam.position.x+=(Math.random()-.5)*impact;cam.position.y+=(Math.random()-.5)*impact;impact*=.78}}
 else if(p==="chase"){const c=t-39;leroy.position.set(Math.sin(c*1.7)*1.7,0,-10-c*4.6);enemy.visible=false;cam.position.lerp(new THREE.Vector3(leroy.position.x*.45,3.2,leroy.position.z+8),.12);cam.lookAt(leroy.position.x,1.5,leroy.position.z-6);blue.intensity=90+Math.sin(c*10)*70;amber.intensity=40+Math.cos(c*10)*25}
 else if(p==="jungle"){enemy.visible=false;crowd.visible=false;speakers.visible=false;scene.background.set(0x020904);scene.fog.color.set(0x07180c);scene.fog.density=.055;road.material=(road.material as THREE.Material);(road.material as THREE.MeshPhysicalMaterial).color.set(0x071408);leroy.position.set(0,0,-58);cam.position.lerp(new THREE.Vector3(0,3.8,-50),.06);cam.lookAt(0,2,-65)}
 else {leroy.visible=false;crowd.visible=false;speakers.visible=false;enemy.visible=false;scene.background.set(0x000000);cam.position.set(0,3,5)}renderer.render(scene,cam)};animate();const resize=()=>{cam.aspect=host.clientWidth/host.clientHeight;cam.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};window.addEventListener("resize",resize);return()=>{dead=true;cancelAnimationFrame(raf);window.removeEventListener("resize",resize);renderer.dispose();host.removeChild(renderer.domElement)}},[time]);
 return <main className="fixed inset-0 bg-black text-white overflow-hidden"><div ref={mount} className="absolute inset-0"/><div className="absolute inset-0 pointer-events-none bg-gradient-to-b from-black/40 via-transparent to-black/70"/><header className="absolute top-0 inset-x-0 p-5 sm:p-8 flex justify-between text-[10px] sm:text-xs tracking-[.24em]"><div><b>BADMAN KOMBAT™</b><br/><span className="text-amber-400">PRE-ALPHA • TARGET GAMEPLAY CONCEPT</span></div><div className="text-right">KINGSTON, JAMAICA<br/>1987</div></header><div className="absolute left-0 right-0 bottom-[18%] text-center"><h1 className="text-3xl sm:text-7xl font-black italic tracking-tight drop-shadow-2xl">{captions[phase]}</h1>{phase==="title"&&<><p className="mt-4 text-xl sm:text-3xl font-black text-amber-400">JAMAICA YOU CAN PLAY™</p><p className="mt-2 tracking-[.3em] text-xs">KINGSTON IS ONLY THE BEGINNING.</p></>}</div><footer className="absolute bottom-0 inset-x-0 p-5 sm:p-8"><div className="h-1 bg-white/20"><div className="h-full bg-amber-400" style={{width:`${time/DURATION*100}%`}}/></div><div className="mt-3 flex justify-between items-center text-[10px] tracking-widest"><div className="pointer-events-auto flex gap-2"><button className="border border-white/30 px-3 py-2" onClick={()=>setPlaying(v=>!v)}>{playing?"PAUSE":"PLAY"}</button><button className="border border-white/20 px-3 py-2" onClick={()=>setTime(0)}>RESTART</button></div><span>AUTO-DIRECTED GAME ENGINE CAPTURE</span><span>{time.toFixed(1)} / 60.0</span></div></footer></main>
}
